name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec ruby -Ilib exe/zestimate '4567 Hampshire Pl, San Jose, CA 95136'
